-- AlterEnum
ALTER TYPE "JobType" ADD VALUE 'META_TITLE_MAINTENANCE';
ALTER TYPE "JobType" ADD VALUE 'MICROSITE_CONTENT_REFRESH';
ALTER TYPE "JobType" ADD VALUE 'MICROSITE_SITEMAP_RESUBMIT';
ALTER TYPE "JobType" ADD VALUE 'COLLECTION_REFRESH';
ALTER TYPE "JobType" ADD VALUE 'AUTONOMOUS_ROADMAP';
