'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Card, CardContent } from '@experience-marketplace/ui-components';

interface Brand {
  id: string;
  name: string;
  tagline: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  headingFont: string;
  bodyFont: string;
  logoUrl: string | null;
  isAutoGenerated: boolean;
}

interface Domain {
  id: string;
  domain: string;
  status: string;
  verifiedAt: string | null;
  sslStatus: string;
}

interface Page {
  id: string;
  title: string;
  slug: string;
  type: string;
  status: string;
}

interface Job {
  id: string;
  type: string;
  status: 'PENDING' | 'SCHEDULED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'RETRYING';
  priority: number;
  attempts: number;
  maxAttempts: number;
  error: string | null;
  result: any;
  scheduledFor: string | null;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
}

interface Site {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  status: string;
  isAutomatic: boolean;
  autonomousProcessesPaused: boolean;
  pauseReason: string | null;
  primaryDomain: string | null;
  suggestedDomain: string;
  gscVerified: boolean;
  gscVerifiedAt: string | null;
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
  brand: Brand | null;
  domains: Domain[];
  pages: Page[];
  counts: {
    pages: number;
    content: number;
    bookings: number;
  };
}

interface JobSummary {
  total: number;
  pending: number;
  running: number;
  completed: number;
  failed: number;
}

// Human-friendly job type labels
const JOB_TYPE_LABELS: Record<string, { label: string; description: string }> = {
  SITE_CREATE: { label: 'Create Site', description: 'Setting up the site structure and brand' },
  CONTENT_GENERATE: { label: 'Generate Content', description: 'Writing page content using AI' },
  CONTENT_OPTIMIZE: { label: 'Optimize Content', description: 'Improving content for SEO' },
  CONTENT_REVIEW: { label: 'Review Content', description: 'Quality checking generated content' },
  DOMAIN_REGISTER: { label: 'Register Domain', description: 'Purchasing the domain name' },
  DOMAIN_VERIFY: { label: 'Verify Domain', description: 'Confirming domain ownership' },
  SSL_PROVISION: { label: 'Setup SSL', description: 'Installing security certificate' },
  GSC_VERIFY: { label: 'Verify Google Search Console', description: 'Connecting to Google Search Console' },
  GSC_SETUP: { label: 'Setup Search Console', description: 'Configuring Google Search Console' },
  GSC_SYNC: { label: 'Sync Search Data', description: 'Fetching data from Google Search Console' },
  SITE_DEPLOY: { label: 'Deploy Site', description: 'Publishing the site to the web' },
  SEO_ANALYZE: { label: 'Analyze SEO', description: 'Checking SEO performance' },
  SEO_OPPORTUNITY_SCAN: { label: 'Scan Opportunities', description: 'Looking for new SEO opportunities' },
  METRICS_AGGREGATE: { label: 'Aggregate Metrics', description: 'Collecting performance data' },
  PERFORMANCE_REPORT: { label: 'Generate Report', description: 'Creating performance report' },
  ABTEST_ANALYZE: { label: 'Analyze A/B Test', description: 'Evaluating test results' },
  ABTEST_REBALANCE: { label: 'Rebalance Traffic', description: 'Adjusting A/B test traffic split' },
};

export default function SiteDetailPage() {
  const params = useParams();
  const router = useRouter();
  const siteId = params.id as string;

  const [site, setSite] = useState<Site | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [jobSummary, setJobSummary] = useState<JobSummary | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'overview' | 'tasks' | 'pages' | 'domains'>('tasks');

  useEffect(() => {
    const fetchSite = async () => {
      try {
        setLoading(true);
        const response = await fetch(`/admin/api/sites/${siteId}`);
        const data = await response.json();

        if (!response.ok || data.error) {
          console.error('API error:', data.error);
          return;
        }

        setSite(data.site);
        setJobs(data.jobs || []);
        setJobSummary(data.jobSummary);
      } catch (error) {
        console.error('Failed to fetch site:', error);
      } finally {
        setLoading(false);
      }
    };

    if (siteId) {
      fetchSite();
    }
  }, [siteId]);

  const getJobStatusBadge = (status: Job['status']) => {
    const styles: Record<Job['status'], string> = {
      PENDING: 'bg-gray-100 text-gray-800',
      SCHEDULED: 'bg-blue-100 text-blue-800',
      RUNNING: 'bg-yellow-100 text-yellow-800 animate-pulse',
      COMPLETED: 'bg-green-100 text-green-800',
      FAILED: 'bg-red-100 text-red-800',
      CANCELLED: 'bg-slate-100 text-slate-800',
      RETRYING: 'bg-orange-100 text-orange-800',
    };
    return (
      <span className={`${styles[status]} text-xs px-2 py-1 rounded font-medium`}>
        {status}
      </span>
    );
  };

  const getJobIcon = (type: string, status: Job['status']) => {
    if (status === 'RUNNING') return '⏳';
    if (status === 'COMPLETED') return '✅';
    if (status === 'FAILED') return '❌';
    if (status === 'PENDING' || status === 'SCHEDULED') return '⏸️';

    // Default icons by type
    const typeIcons: Record<string, string> = {
      SITE_CREATE: '🏗️',
      CONTENT_GENERATE: '✍️',
      CONTENT_OPTIMIZE: '📈',
      DOMAIN_REGISTER: '🌐',
      DOMAIN_VERIFY: '✓',
      SSL_PROVISION: '🔒',
      GSC_VERIFY: '🔍',
      GSC_SETUP: '⚙️',
      GSC_SYNC: '🔄',
      SITE_DEPLOY: '🚀',
      SEO_ANALYZE: '📊',
      METRICS_AGGREGATE: '📉',
    };
    return typeIcons[type] || '📋';
  };

  const formatDate = (dateStr: string | null) => {
    if (!dateStr) return '-';
    const date = new Date(dateStr);
    return date.toLocaleString();
  };

  const formatRelativeTime = (dateStr: string) => {
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-slate-500">Loading site details...</div>
      </div>
    );
  }

  if (!site) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-4">
        <div className="text-slate-500">Site not found</div>
        <button
          onClick={() => router.push('/admin/sites')}
          className="text-sky-600 hover:underline"
        >
          Back to Sites
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start gap-4">
        <button
          onClick={() => router.push('/admin/sites')}
          className="mt-1 text-slate-400 hover:text-slate-600"
        >
          ← Back
        </button>
        <div className="flex-1">
          <div className="flex items-center gap-4">
            {/* Logo */}
            <div
              className="w-16 h-16 rounded-lg flex items-center justify-center text-white text-2xl font-bold shrink-0"
              style={{ backgroundColor: site.brand?.primaryColor || '#6366f1' }}
            >
              {site.brand?.logoUrl ? (
                <img
                  src={site.brand.logoUrl}
                  alt={site.name}
                  className="w-full h-full object-contain rounded-lg"
                />
              ) : (
                site.name.charAt(0).toUpperCase()
              )}
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">{site.name}</h1>
              {site.brand?.tagline && (
                <p className="text-slate-600 italic">&ldquo;{site.brand.tagline}&rdquo;</p>
              )}
              <p className="text-sm text-slate-500">
                {site.primaryDomain || site.suggestedDomain}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Task Summary Cards */}
      {jobSummary && (
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-slate-900">{jobSummary.total}</p>
              <p className="text-sm text-slate-500">Total Tasks</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-yellow-600">{jobSummary.running}</p>
              <p className="text-sm text-slate-500">Running</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-blue-600">{jobSummary.pending}</p>
              <p className="text-sm text-slate-500">Pending</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-green-600">{jobSummary.completed}</p>
              <p className="text-sm text-slate-500">Completed</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-red-600">{jobSummary.failed}</p>
              <p className="text-sm text-slate-500">Failed</p>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Tabs */}
      <div className="border-b border-slate-200">
        <nav className="flex gap-4">
          {(['tasks', 'overview', 'pages', 'domains'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors ${
                activeTab === tab
                  ? 'border-sky-600 text-sky-600'
                  : 'border-transparent text-slate-500 hover:text-slate-700'
              }`}
            >
              {tab.charAt(0).toUpperCase() + tab.slice(1)}
            </button>
          ))}
        </nav>
      </div>

      {/* Tasks Tab */}
      {activeTab === 'tasks' && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-900">Task History</h2>
            <p className="text-sm text-slate-500">
              Showing {jobs.length} recent tasks
            </p>
          </div>

          {jobs.length === 0 ? (
            <Card>
              <CardContent className="p-8 text-center">
                <div className="text-4xl mb-4">📋</div>
                <h3 className="text-lg font-medium text-slate-900">No tasks yet</h3>
                <p className="text-slate-500 mt-1">
                  Tasks will appear here as the system works on this site
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {jobs.map((job) => {
                const jobInfo = JOB_TYPE_LABELS[job.type] || {
                  label: job.type,
                  description: 'Processing task',
                };

                return (
                  <Card key={job.id} className="hover:shadow-md transition-shadow">
                    <CardContent className="p-4">
                      <div className="flex items-start gap-4">
                        {/* Icon */}
                        <div className="text-2xl">{getJobIcon(job.type, job.status)}</div>

                        {/* Content */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-3 mb-1">
                            <h3 className="font-medium text-slate-900">{jobInfo.label}</h3>
                            {getJobStatusBadge(job.status)}
                          </div>
                          <p className="text-sm text-slate-500 mb-2">{jobInfo.description}</p>

                          {/* Error message if failed */}
                          {job.status === 'FAILED' && job.error && (
                            <div className="mt-2 p-2 bg-red-50 rounded text-sm text-red-700">
                              {job.error}
                            </div>
                          )}

                          {/* Timing info */}
                          <div className="flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400">
                            <span>Created: {formatRelativeTime(job.createdAt)}</span>
                            {job.startedAt && (
                              <span>Started: {formatRelativeTime(job.startedAt)}</span>
                            )}
                            {job.completedAt && (
                              <span>Completed: {formatRelativeTime(job.completedAt)}</span>
                            )}
                            {job.attempts > 1 && (
                              <span>
                                Attempts: {job.attempts}/{job.maxAttempts}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </div>
      )}

      {/* Overview Tab */}
      {activeTab === 'overview' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Site Info */}
          <Card>
            <CardContent className="p-6">
              <h3 className="text-lg font-semibold text-slate-900 mb-4">Site Information</h3>
              <dl className="space-y-3">
                <div className="flex justify-between">
                  <dt className="text-slate-500">Status</dt>
                  <dd className="font-medium">{site.status}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">Mode</dt>
                  <dd className="font-medium">{site.isAutomatic ? 'Automatic' : 'Manual'}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">Domain</dt>
                  <dd className="font-medium">{site.primaryDomain || site.suggestedDomain}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">GSC Verified</dt>
                  <dd className="font-medium">{site.gscVerified ? 'Yes' : 'No'}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">Created</dt>
                  <dd className="font-medium">{formatDate(site.createdAt)}</dd>
                </div>
              </dl>
            </CardContent>
          </Card>

          {/* Brand Info */}
          {site.brand && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-lg font-semibold text-slate-900 mb-4">Brand Identity</h3>
                <dl className="space-y-3">
                  <div className="flex justify-between">
                    <dt className="text-slate-500">Name</dt>
                    <dd className="font-medium">{site.brand.name}</dd>
                  </div>
                  {site.brand.tagline && (
                    <div className="flex justify-between">
                      <dt className="text-slate-500">Tagline</dt>
                      <dd className="font-medium text-right max-w-[200px]">{site.brand.tagline}</dd>
                    </div>
                  )}
                  <div className="flex justify-between items-center">
                    <dt className="text-slate-500">Colors</dt>
                    <dd className="flex gap-2">
                      <div
                        className="w-8 h-8 rounded border"
                        style={{ backgroundColor: site.brand.primaryColor }}
                        title={`Primary: ${site.brand.primaryColor}`}
                      />
                      <div
                        className="w-8 h-8 rounded border"
                        style={{ backgroundColor: site.brand.secondaryColor }}
                        title={`Secondary: ${site.brand.secondaryColor}`}
                      />
                      <div
                        className="w-8 h-8 rounded border"
                        style={{ backgroundColor: site.brand.accentColor }}
                        title={`Accent: ${site.brand.accentColor}`}
                      />
                    </dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-slate-500">Fonts</dt>
                    <dd className="font-medium">
                      {site.brand.headingFont}
                      {site.brand.bodyFont !== site.brand.headingFont && ` / ${site.brand.bodyFont}`}
                    </dd>
                  </div>
                  {site.brand.isAutoGenerated && (
                    <div className="pt-2 text-xs text-slate-400">✨ AI-generated brand</div>
                  )}
                </dl>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Pages Tab */}
      {activeTab === 'pages' && (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-slate-900">Pages ({site.pages.length})</h2>
          {site.pages.length === 0 ? (
            <Card>
              <CardContent className="p-8 text-center">
                <div className="text-4xl mb-4">📄</div>
                <h3 className="text-lg font-medium text-slate-900">No pages yet</h3>
                <p className="text-slate-500 mt-1">Pages will be created as content is generated</p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-3">
              {site.pages.map((page) => (
                <Card key={page.id}>
                  <CardContent className="p-4 flex items-center justify-between">
                    <div>
                      <h3 className="font-medium text-slate-900">{page.title}</h3>
                      <p className="text-sm text-slate-500">/{page.slug || '(homepage)'}</p>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-xs text-slate-400">{page.type}</span>
                      <span
                        className={`text-xs px-2 py-1 rounded ${
                          page.status === 'PUBLISHED'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-gray-100 text-gray-800'
                        }`}
                      >
                        {page.status}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Domains Tab */}
      {activeTab === 'domains' && (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-slate-900">Domains</h2>

          {/* Suggested domain */}
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-medium text-slate-900">{site.suggestedDomain}</h3>
                  <p className="text-sm text-slate-500">
                    {site.primaryDomain ? 'Primary domain' : 'Suggested domain (not yet registered)'}
                  </p>
                </div>
                <span
                  className={`text-xs px-2 py-1 rounded ${
                    site.primaryDomain ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'
                  }`}
                >
                  {site.primaryDomain ? 'Active' : 'Pending'}
                </span>
              </div>
            </CardContent>
          </Card>

          {/* Registered domains */}
          {site.domains.length > 0 && (
            <>
              <h3 className="text-md font-medium text-slate-700 mt-6">Registered Domains</h3>
              {site.domains.map((domain) => (
                <Card key={domain.id}>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <h3 className="font-medium text-slate-900">{domain.domain}</h3>
                        <p className="text-sm text-slate-500">
                          SSL: {domain.sslStatus || 'Not configured'}
                          {domain.verifiedAt && ` • Verified ${formatDate(domain.verifiedAt)}`}
                        </p>
                      </div>
                      <span
                        className={`text-xs px-2 py-1 rounded ${
                          domain.status === 'ACTIVE'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-gray-100 text-gray-800'
                        }`}
                      >
                        {domain.status}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </>
          )}
        </div>
      )}
    </div>
  );
}
