'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent } from '@experience-marketplace/ui-components';

interface Brand {
  id: string;
  name: string;
  tagline: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  headingFont: string;
  bodyFont: string;
  logoUrl: string | null;
  isAutoGenerated: boolean;
}

// Brand identity data stored in seoConfig
interface ToneOfVoice {
  personality?: string[];
  writingStyle?: string;
  doList?: string[];
  dontList?: string[];
}

interface TrustSignals {
  expertise?: string[];
  certifications?: string[];
  yearsFounded?: number;
  valuePropositions?: string[];
  guarantees?: string[];
}

interface BrandStory {
  mission?: string;
  vision?: string;
  values?: string[];
  targetAudience?: string;
  uniqueSellingPoints?: string[];
}

interface ContentGuidelines {
  keyThemes?: string[];
  contentPillars?: string[];
  semanticKeywords?: string[];
}

interface SeoConfig {
  toneOfVoice?: ToneOfVoice;
  trustSignals?: TrustSignals;
  brandStory?: BrandStory;
  contentGuidelines?: ContentGuidelines;
}

interface Domain {
  id: string;
  domain: string;
  status: string;
  verifiedAt: string | null;
  sslEnabled: boolean;
}

interface Page {
  id: string;
  title: string;
  slug: string;
  type: string;
  status: string;
}

interface Job {
  id: string;
  type: string;
  status: 'PENDING' | 'SCHEDULED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'RETRYING';
  priority: number;
  attempts: number;
  maxAttempts: number;
  error: string | null;
  result: any;
  scheduledFor: string | null;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
}

interface Site {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  status: string;
  isAutomatic: boolean;
  autonomousProcessesPaused: boolean;
  pauseReason: string | null;
  primaryDomain: string | null;
  suggestedDomain: string;
  gscVerified: boolean;
  gscVerifiedAt: string | null;
  seoConfig: SeoConfig | null;
  createdAt: string;
  updatedAt: string;
  publishedAt: string | null;
  brand: Brand | null;
  domains: Domain[];
  pages: Page[];
  counts: {
    pages: number;
    content: number;
    bookings: number;
  };
}

interface JobSummary {
  total: number;
  pending: number;
  running: number;
  completed: number;
  failed: number;
}

interface RoadmapTask {
  type: string;
  label: string;
  description: string;
  status: 'PLANNED' | 'PENDING' | 'SCHEDULED' | 'RUNNING' | 'COMPLETED' | 'FAILED';
  job: {
    id: string;
    status: string;
    startedAt: string | null;
    completedAt: string | null;
    error: string | null;
    attempts: number;
  } | null;
}

interface RoadmapPhase {
  key: string;
  name: string;
  description: string;
  status: 'pending' | 'in_progress' | 'completed' | 'failed';
  progress: {
    completed: number;
    total: number;
    percentage: number;
  };
  tasks: RoadmapTask[];
}

interface Roadmap {
  siteId: string;
  phases: RoadmapPhase[];
  overall: {
    completed: number;
    total: number;
    percentage: number;
  };
}

// Human-friendly job type labels
const JOB_TYPE_LABELS: Record<string, { label: string; description: string }> = {
  SITE_CREATE: { label: 'Create Site', description: 'Setting up the site structure and brand' },
  CONTENT_GENERATE: { label: 'Generate Content', description: 'Writing page content using AI' },
  CONTENT_OPTIMIZE: { label: 'Optimize Content', description: 'Improving content for SEO' },
  CONTENT_REVIEW: { label: 'Review Content', description: 'Quality checking generated content' },
  DOMAIN_REGISTER: { label: 'Register Domain', description: 'Purchasing the domain name' },
  DOMAIN_VERIFY: { label: 'Verify Domain', description: 'Confirming domain ownership' },
  SSL_PROVISION: { label: 'Setup SSL', description: 'Installing security certificate' },
  GSC_VERIFY: { label: 'Verify Google Search Console', description: 'Connecting to Google Search Console' },
  GSC_SETUP: { label: 'Setup Search Console', description: 'Configuring Google Search Console' },
  GSC_SYNC: { label: 'Sync Search Data', description: 'Fetching data from Google Search Console' },
  SITE_DEPLOY: { label: 'Deploy Site', description: 'Publishing the site to the web' },
  SEO_ANALYZE: { label: 'Analyze SEO', description: 'Checking SEO performance' },
  SEO_OPPORTUNITY_SCAN: { label: 'Scan Opportunities', description: 'Looking for new SEO opportunities' },
  METRICS_AGGREGATE: { label: 'Aggregate Metrics', description: 'Collecting performance data' },
  PERFORMANCE_REPORT: { label: 'Generate Report', description: 'Creating performance report' },
  ABTEST_ANALYZE: { label: 'Analyze A/B Test', description: 'Evaluating test results' },
  ABTEST_REBALANCE: { label: 'Rebalance Traffic', description: 'Adjusting A/B test traffic split' },
};

interface SiteDetailClientProps {
  siteId: string;
}

export default function SiteDetailClient({ siteId }: SiteDetailClientProps) {
  const router = useRouter();

  const [site, setSite] = useState<Site | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [jobSummary, setJobSummary] = useState<JobSummary | null>(null);
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null);
  const [loading, setLoading] = useState(true);
  const [initializingRoadmap, setInitializingRoadmap] = useState(false);
  const [executingTasks, setExecutingTasks] = useState(false);
  const [activeTab, setActiveTab] = useState<'overview' | 'roadmap' | 'brand' | 'pages' | 'domains'>('roadmap');

  useEffect(() => {
    const fetchSite = async () => {
      try {
        setLoading(true);
        const response = await fetch(`/admin/api/sites/${siteId}`);
        const data = await response.json();

        if (!response.ok || data.error) {
          console.error('API error:', data.error);
          return;
        }

        setSite(data.site);
        setJobs(data.jobs || []);
        setJobSummary(data.jobSummary);
        setRoadmap(data.roadmap || null);
      } catch (error) {
        console.error('Failed to fetch site:', error);
      } finally {
        setLoading(false);
      }
    };

    if (siteId) {
      fetchSite();
    }
  }, [siteId]);

  const getJobStatusBadge = (status: Job['status']) => {
    const styles: Record<Job['status'], string> = {
      PENDING: 'bg-gray-100 text-gray-800',
      SCHEDULED: 'bg-blue-100 text-blue-800',
      RUNNING: 'bg-yellow-100 text-yellow-800 animate-pulse',
      COMPLETED: 'bg-green-100 text-green-800',
      FAILED: 'bg-red-100 text-red-800',
      CANCELLED: 'bg-slate-100 text-slate-800',
      RETRYING: 'bg-orange-100 text-orange-800',
    };
    return (
      <span className={`${styles[status]} text-xs px-2 py-1 rounded font-medium`}>
        {status}
      </span>
    );
  };

  const getJobIcon = (type: string, status: Job['status']) => {
    if (status === 'RUNNING') return '⏳';
    if (status === 'COMPLETED') return '✅';
    if (status === 'FAILED') return '❌';
    if (status === 'PENDING' || status === 'SCHEDULED') return '⏸️';

    // Default icons by type
    const typeIcons: Record<string, string> = {
      SITE_CREATE: '🏗️',
      CONTENT_GENERATE: '✍️',
      CONTENT_OPTIMIZE: '📈',
      DOMAIN_REGISTER: '🌐',
      DOMAIN_VERIFY: '✓',
      SSL_PROVISION: '🔒',
      GSC_VERIFY: '🔍',
      GSC_SETUP: '⚙️',
      GSC_SYNC: '🔄',
      SITE_DEPLOY: '🚀',
      SEO_ANALYZE: '📊',
      METRICS_AGGREGATE: '📉',
    };
    return typeIcons[type] || '📋';
  };

  const formatDate = (dateStr: string | null) => {
    if (!dateStr) return '-';
    const date = new Date(dateStr);
    return date.toLocaleString();
  };

  const formatRelativeTime = (dateStr: string) => {
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 1) return 'just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-slate-500">Loading site details...</div>
      </div>
    );
  }

  if (!site) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-4">
        <div className="text-slate-500">Site not found</div>
        <button
          onClick={() => router.push('/sites')}
          className="text-sky-600 hover:underline"
        >
          Back to Sites
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start gap-4">
        <button
          onClick={() => router.push('/sites')}
          className="mt-1 text-slate-400 hover:text-slate-600"
        >
          ← Back
        </button>
        <div className="flex-1">
          <div className="flex items-center gap-4">
            {/* Logo */}
            <div
              className="w-16 h-16 rounded-lg flex items-center justify-center text-white text-2xl font-bold shrink-0"
              style={{ backgroundColor: site.brand?.primaryColor || '#6366f1' }}
            >
              {site.brand?.logoUrl ? (
                <img
                  src={site.brand.logoUrl}
                  alt={site.name}
                  className="w-full h-full object-contain rounded-lg"
                />
              ) : (
                site.name.charAt(0).toUpperCase()
              )}
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">{site.name}</h1>
              {site.brand?.tagline && (
                <p className="text-slate-600 italic">&ldquo;{site.brand.tagline}&rdquo;</p>
              )}
              <p className="text-sm text-slate-500">
                {site.primaryDomain || site.suggestedDomain}
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Task Summary Cards */}
      {jobSummary && (
        <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-slate-900">{jobSummary.total}</p>
              <p className="text-sm text-slate-500">Total Tasks</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-yellow-600">{jobSummary.running}</p>
              <p className="text-sm text-slate-500">Running</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-blue-600">{jobSummary.pending}</p>
              <p className="text-sm text-slate-500">Pending</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-green-600">{jobSummary.completed}</p>
              <p className="text-sm text-slate-500">Completed</p>
            </CardContent>
          </Card>
          <Card className="cursor-pointer hover:shadow-md transition-shadow">
            <CardContent className="p-4">
              <p className="text-2xl font-bold text-red-600">{jobSummary.failed}</p>
              <p className="text-sm text-slate-500">Failed</p>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Tabs */}
      <div className="border-b border-slate-200">
        <nav className="flex gap-4">
          {(['roadmap', 'overview', 'brand', 'pages', 'domains'] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors ${
                activeTab === tab
                  ? 'border-sky-600 text-sky-600'
                  : 'border-transparent text-slate-500 hover:text-slate-700'
              }`}
            >
              {tab.charAt(0).toUpperCase() + tab.slice(1)}
            </button>
          ))}
        </nav>
      </div>

      {/* Roadmap Tab */}
      {activeTab === 'roadmap' && (
        <div className="space-y-6">
          {/* Overall Progress */}
          {roadmap && (
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h2 className="text-lg font-semibold text-slate-900">Site Launch Progress</h2>
                    <p className="text-sm text-slate-500">Track all tasks needed to get your site live</p>
                  </div>
                  <div className="text-right">
                    <div className="text-3xl font-bold text-sky-600">{roadmap.overall.percentage}%</div>
                    <div className="text-sm text-slate-500">
                      {roadmap.overall.completed} of {roadmap.overall.total} tasks
                    </div>
                  </div>
                </div>
                <div className="w-full bg-slate-200 rounded-full h-3">
                  <div
                    className="bg-sky-600 h-3 rounded-full transition-all duration-500"
                    style={{ width: `${roadmap.overall.percentage}%` }}
                  />
                </div>

                {/* Execute Tasks Button */}
                {roadmap.overall.percentage < 100 && (
                  <div className="mt-4 pt-4 border-t border-slate-100">
                    <button
                      onClick={async () => {
                        setExecutingTasks(true);
                        try {
                          const response = await fetch(`/admin/api/sites/${siteId}/execute-tasks`, {
                            method: 'POST',
                          });
                          const result = await response.json();

                          if (response.ok) {
                            // Show result
                            if (result.queued?.length > 0) {
                              alert(`Queued ${result.queued.length} task(s): ${result.queued.join(', ')}`);
                            } else {
                              alert(result.message || 'No tasks could be queued');
                            }

                            // Refetch to update roadmap
                            const siteResponse = await fetch(`/admin/api/sites/${siteId}`);
                            const data = await siteResponse.json();
                            if (siteResponse.ok) {
                              setSite(data.site);
                              setRoadmap(data.roadmap || null);
                              setJobs(data.jobs || []);
                              setJobSummary(data.jobSummary);
                            }
                          } else {
                            alert(result.error || 'Failed to execute tasks');
                          }
                        } catch (error) {
                          console.error('Failed to execute tasks:', error);
                          alert('Failed to execute tasks');
                        } finally {
                          setExecutingTasks(false);
                        }
                      }}
                      disabled={executingTasks}
                      className="w-full px-4 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 flex items-center justify-center gap-2"
                    >
                      {executingTasks ? (
                        <>
                          <span className="animate-spin">&#9696;</span>
                          Executing...
                        </>
                      ) : (
                        <>
                          <span>&#9654;</span>
                          Execute Next Tasks
                        </>
                      )}
                    </button>
                    <p className="text-xs text-slate-500 text-center mt-2">
                      Queues pending tasks that have all dependencies met
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {/* Phases */}
          {roadmap?.phases.map((phase, phaseIndex) => {
            const phaseStatusStyles = {
              pending: 'border-slate-200 bg-slate-50',
              in_progress: 'border-sky-200 bg-sky-50',
              completed: 'border-green-200 bg-green-50',
              failed: 'border-red-200 bg-red-50',
            };

            const phaseStatusIcons = {
              pending: '⏸️',
              in_progress: '▶️',
              completed: '✅',
              failed: '❌',
            };

            return (
              <Card key={phase.key} className={`border-2 ${phaseStatusStyles[phase.status]}`}>
                <CardContent className="p-0">
                  {/* Phase Header */}
                  <div className="p-4 border-b border-slate-100">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <span className="text-2xl">{phaseStatusIcons[phase.status]}</span>
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="text-sm text-slate-400 font-medium">Phase {phaseIndex + 1}</span>
                            <h3 className="font-semibold text-slate-900">{phase.name}</h3>
                          </div>
                          <p className="text-sm text-slate-500">{phase.description}</p>
                        </div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm font-medium text-slate-700">
                          {phase.progress.completed}/{phase.progress.total}
                        </div>
                        <div className="w-24 bg-slate-200 rounded-full h-2 mt-1">
                          <div
                            className={`h-2 rounded-full transition-all duration-500 ${
                              phase.status === 'completed'
                                ? 'bg-green-500'
                                : phase.status === 'failed'
                                ? 'bg-red-500'
                                : 'bg-sky-500'
                            }`}
                            style={{ width: `${phase.progress.percentage}%` }}
                          />
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Phase Tasks */}
                  <div className="divide-y divide-slate-100">
                    {phase.tasks.map((task) => {
                      const taskStatusStyles: Record<string, string> = {
                        PLANNED: 'text-slate-400',
                        PENDING: 'text-slate-600',
                        SCHEDULED: 'text-blue-600',
                        RUNNING: 'text-yellow-600',
                        COMPLETED: 'text-green-600',
                        FAILED: 'text-red-600',
                      };

                      const taskStatusBadges: Record<string, string> = {
                        PLANNED: 'bg-slate-100 text-slate-600',
                        PENDING: 'bg-gray-100 text-gray-800',
                        SCHEDULED: 'bg-blue-100 text-blue-800',
                        RUNNING: 'bg-yellow-100 text-yellow-800 animate-pulse',
                        COMPLETED: 'bg-green-100 text-green-800',
                        FAILED: 'bg-red-100 text-red-800',
                      };

                      const taskStatusIcons: Record<string, string> = {
                        PLANNED: '○',
                        PENDING: '◔',
                        SCHEDULED: '◑',
                        RUNNING: '◕',
                        COMPLETED: '●',
                        FAILED: '✗',
                      };

                      return (
                        <div key={task.type} className="px-4 py-3 flex items-center gap-4">
                          <span className={`text-xl ${taskStatusStyles[task.status]}`}>
                            {taskStatusIcons[task.status]}
                          </span>
                          <div className="flex-1 min-w-0">
                            <div className="flex items-center gap-2">
                              <span className="font-medium text-slate-900">{task.label}</span>
                              <span className={`text-xs px-2 py-0.5 rounded ${taskStatusBadges[task.status]}`}>
                                {task.status === 'PLANNED' ? 'Planned' : task.status}
                              </span>
                            </div>
                            <p className="text-sm text-slate-500">{task.description}</p>
                            {task.job?.error && task.status === 'FAILED' && (
                              <p className="text-xs text-red-600 mt-1">{task.job.error}</p>
                            )}
                          </div>
                          {task.job?.completedAt && task.status === 'COMPLETED' && (
                            <span className="text-xs text-slate-400">
                              {formatRelativeTime(task.job.completedAt)}
                            </span>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </CardContent>
              </Card>
            );
          })}

          {/* No roadmap fallback */}
          {!roadmap && (
            <Card>
              <CardContent className="p-8 text-center">
                <div className="text-4xl mb-4">🗺️</div>
                <h3 className="text-lg font-medium text-slate-900">No roadmap available</h3>
                <p className="text-slate-500 mt-1 mb-4">
                  Initialize the site launch roadmap to track progress
                </p>
                <button
                  onClick={async () => {
                    setInitializingRoadmap(true);
                    try {
                      const response = await fetch(`/admin/api/sites/${siteId}/initialize-roadmap`, {
                        method: 'POST',
                      });
                      if (response.ok) {
                        // Refetch site data to get the new roadmap
                        const siteResponse = await fetch(`/admin/api/sites/${siteId}`);
                        const data = await siteResponse.json();
                        if (siteResponse.ok) {
                          setSite(data.site);
                          setRoadmap(data.roadmap || null);
                        }
                      }
                    } catch (error) {
                      console.error('Failed to initialize roadmap:', error);
                    } finally {
                      setInitializingRoadmap(false);
                    }
                  }}
                  disabled={initializingRoadmap}
                  className="px-4 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
                >
                  {initializingRoadmap ? 'Initializing...' : 'Initialize Roadmap'}
                </button>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Overview Tab */}
      {activeTab === 'overview' && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Site Info */}
          <Card>
            <CardContent className="p-6">
              <h3 className="text-lg font-semibold text-slate-900 mb-4">Site Information</h3>
              <dl className="space-y-3">
                <div className="flex justify-between">
                  <dt className="text-slate-500">Status</dt>
                  <dd className="font-medium">{site.status}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">Mode</dt>
                  <dd className="font-medium">{site.isAutomatic ? 'Automatic' : 'Manual'}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">Domain</dt>
                  <dd className="font-medium">{site.primaryDomain || site.suggestedDomain}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">GSC Verified</dt>
                  <dd className="font-medium">{site.gscVerified ? 'Yes' : 'No'}</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-slate-500">Created</dt>
                  <dd className="font-medium">{formatDate(site.createdAt)}</dd>
                </div>
              </dl>
            </CardContent>
          </Card>

          {/* Brand Info */}
          {site.brand && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-lg font-semibold text-slate-900 mb-4">Brand Identity</h3>
                <dl className="space-y-3">
                  <div className="flex justify-between">
                    <dt className="text-slate-500">Name</dt>
                    <dd className="font-medium">{site.brand.name}</dd>
                  </div>
                  {site.brand.tagline && (
                    <div className="flex justify-between">
                      <dt className="text-slate-500">Tagline</dt>
                      <dd className="font-medium text-right max-w-[200px]">{site.brand.tagline}</dd>
                    </div>
                  )}
                  <div className="flex justify-between items-center">
                    <dt className="text-slate-500">Colors</dt>
                    <dd className="flex gap-2">
                      <div
                        className="w-8 h-8 rounded border"
                        style={{ backgroundColor: site.brand.primaryColor }}
                        title={`Primary: ${site.brand.primaryColor}`}
                      />
                      <div
                        className="w-8 h-8 rounded border"
                        style={{ backgroundColor: site.brand.secondaryColor }}
                        title={`Secondary: ${site.brand.secondaryColor}`}
                      />
                      <div
                        className="w-8 h-8 rounded border"
                        style={{ backgroundColor: site.brand.accentColor }}
                        title={`Accent: ${site.brand.accentColor}`}
                      />
                    </dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-slate-500">Fonts</dt>
                    <dd className="font-medium">
                      {site.brand.headingFont}
                      {site.brand.bodyFont !== site.brand.headingFont && ` / ${site.brand.bodyFont}`}
                    </dd>
                  </div>
                  {site.brand.isAutoGenerated && (
                    <div className="pt-2 text-xs text-slate-400">✨ AI-generated brand</div>
                  )}
                </dl>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Brand Tab - Comprehensive Brand Identity */}
      {activeTab === 'brand' && (
        <div className="space-y-6">
          <h2 className="text-lg font-semibold text-slate-900">Brand Identity</h2>

          {/* Basic Brand Info */}
          {site.brand && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-md font-semibold text-slate-900 mb-4">Visual Identity</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <dl className="space-y-3">
                      <div className="flex justify-between">
                        <dt className="text-slate-500">Brand Name</dt>
                        <dd className="font-medium">{site.brand.name}</dd>
                      </div>
                      {site.brand.tagline && (
                        <div>
                          <dt className="text-slate-500 mb-1">Tagline</dt>
                          <dd className="font-medium italic text-slate-700">&ldquo;{site.brand.tagline}&rdquo;</dd>
                        </div>
                      )}
                      <div className="flex justify-between">
                        <dt className="text-slate-500">Typography</dt>
                        <dd className="font-medium">
                          {site.brand.headingFont}
                          {site.brand.bodyFont !== site.brand.headingFont && ` / ${site.brand.bodyFont}`}
                        </dd>
                      </div>
                    </dl>
                  </div>
                  <div>
                    <dt className="text-slate-500 mb-2">Color Palette</dt>
                    <div className="flex gap-3">
                      <div className="text-center">
                        <div
                          className="w-12 h-12 rounded-lg border shadow-sm"
                          style={{ backgroundColor: site.brand.primaryColor }}
                        />
                        <span className="text-xs text-slate-500 mt-1 block">Primary</span>
                      </div>
                      <div className="text-center">
                        <div
                          className="w-12 h-12 rounded-lg border shadow-sm"
                          style={{ backgroundColor: site.brand.secondaryColor }}
                        />
                        <span className="text-xs text-slate-500 mt-1 block">Secondary</span>
                      </div>
                      <div className="text-center">
                        <div
                          className="w-12 h-12 rounded-lg border shadow-sm"
                          style={{ backgroundColor: site.brand.accentColor }}
                        />
                        <span className="text-xs text-slate-500 mt-1 block">Accent</span>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Tone of Voice */}
          {site.seoConfig?.toneOfVoice && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-md font-semibold text-slate-900 mb-4">Tone of Voice</h3>
                <div className="space-y-4">
                  {site.seoConfig.toneOfVoice.personality && site.seoConfig.toneOfVoice.personality.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Personality Traits</dt>
                      <div className="flex flex-wrap gap-2">
                        {site.seoConfig.toneOfVoice.personality.map((trait, i) => (
                          <span key={i} className="px-3 py-1 bg-purple-100 text-purple-800 rounded-full text-sm">
                            {trait}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {site.seoConfig.toneOfVoice.writingStyle && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-1">Writing Style</dt>
                      <dd className="text-slate-700">{site.seoConfig.toneOfVoice.writingStyle}</dd>
                    </div>
                  )}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {site.seoConfig.toneOfVoice.doList && site.seoConfig.toneOfVoice.doList.length > 0 && (
                      <div>
                        <dt className="text-green-700 text-sm font-medium mb-2">Do</dt>
                        <ul className="space-y-1">
                          {site.seoConfig.toneOfVoice.doList.map((item, i) => (
                            <li key={i} className="text-sm text-slate-600 flex items-start gap-2">
                              <span className="text-green-500 mt-0.5">+</span>
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                    {site.seoConfig.toneOfVoice.dontList && site.seoConfig.toneOfVoice.dontList.length > 0 && (
                      <div>
                        <dt className="text-red-700 text-sm font-medium mb-2">Don&apos;t</dt>
                        <ul className="space-y-1">
                          {site.seoConfig.toneOfVoice.dontList.map((item, i) => (
                            <li key={i} className="text-sm text-slate-600 flex items-start gap-2">
                              <span className="text-red-500 mt-0.5">-</span>
                              {item}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Brand Story */}
          {site.seoConfig?.brandStory && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-md font-semibold text-slate-900 mb-4">Brand Story</h3>
                <div className="space-y-4">
                  {site.seoConfig.brandStory.mission && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-1">Mission</dt>
                      <dd className="text-slate-700">{site.seoConfig.brandStory.mission}</dd>
                    </div>
                  )}
                  {site.seoConfig.brandStory.vision && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-1">Vision</dt>
                      <dd className="text-slate-700">{site.seoConfig.brandStory.vision}</dd>
                    </div>
                  )}
                  {site.seoConfig.brandStory.targetAudience && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-1">Target Audience</dt>
                      <dd className="text-slate-700">{site.seoConfig.brandStory.targetAudience}</dd>
                    </div>
                  )}
                  {site.seoConfig.brandStory.values && site.seoConfig.brandStory.values.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Core Values</dt>
                      <div className="flex flex-wrap gap-2">
                        {site.seoConfig.brandStory.values.map((value, i) => (
                          <span key={i} className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm">
                            {value}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {site.seoConfig.brandStory.uniqueSellingPoints && site.seoConfig.brandStory.uniqueSellingPoints.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Unique Selling Points</dt>
                      <ul className="space-y-1">
                        {site.seoConfig.brandStory.uniqueSellingPoints.map((usp, i) => (
                          <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                            <span className="text-sky-500 mt-0.5">*</span>
                            {usp}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Trust Signals */}
          {site.seoConfig?.trustSignals && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-md font-semibold text-slate-900 mb-4">Trust Signals</h3>
                <div className="space-y-4">
                  {site.seoConfig.trustSignals.expertise && site.seoConfig.trustSignals.expertise.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Areas of Expertise</dt>
                      <div className="flex flex-wrap gap-2">
                        {site.seoConfig.trustSignals.expertise.map((exp, i) => (
                          <span key={i} className="px-3 py-1 bg-amber-100 text-amber-800 rounded-full text-sm">
                            {exp}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {site.seoConfig.trustSignals.valuePropositions && site.seoConfig.trustSignals.valuePropositions.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Value Propositions</dt>
                      <ul className="space-y-1">
                        {site.seoConfig.trustSignals.valuePropositions.map((prop, i) => (
                          <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                            <span className="text-green-500 mt-0.5">+</span>
                            {prop}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {site.seoConfig.trustSignals.guarantees && site.seoConfig.trustSignals.guarantees.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Guarantees</dt>
                      <ul className="space-y-1">
                        {site.seoConfig.trustSignals.guarantees.map((guarantee, i) => (
                          <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                            <span className="text-sky-500 mt-0.5">~</span>
                            {guarantee}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {site.seoConfig.trustSignals.certifications && site.seoConfig.trustSignals.certifications.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Certifications</dt>
                      <div className="flex flex-wrap gap-2">
                        {site.seoConfig.trustSignals.certifications.map((cert, i) => (
                          <span key={i} className="px-3 py-1 bg-green-100 text-green-800 rounded-full text-sm">
                            {cert}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Content Guidelines */}
          {site.seoConfig?.contentGuidelines && (
            <Card>
              <CardContent className="p-6">
                <h3 className="text-md font-semibold text-slate-900 mb-4">Content Guidelines</h3>
                <div className="space-y-4">
                  {site.seoConfig.contentGuidelines.keyThemes && site.seoConfig.contentGuidelines.keyThemes.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Key Themes</dt>
                      <div className="flex flex-wrap gap-2">
                        {site.seoConfig.contentGuidelines.keyThemes.map((theme, i) => (
                          <span key={i} className="px-3 py-1 bg-indigo-100 text-indigo-800 rounded-full text-sm">
                            {theme}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                  {site.seoConfig.contentGuidelines.contentPillars && site.seoConfig.contentGuidelines.contentPillars.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Content Pillars</dt>
                      <ul className="space-y-1">
                        {site.seoConfig.contentGuidelines.contentPillars.map((pillar, i) => (
                          <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                            <span className="text-indigo-500 mt-0.5">▸</span>
                            {pillar}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {site.seoConfig.contentGuidelines.semanticKeywords && site.seoConfig.contentGuidelines.semanticKeywords.length > 0 && (
                    <div>
                      <dt className="text-slate-500 text-sm mb-2">Semantic Keywords</dt>
                      <div className="flex flex-wrap gap-2">
                        {site.seoConfig.contentGuidelines.semanticKeywords.map((keyword, i) => (
                          <span key={i} className="px-2 py-0.5 bg-slate-100 text-slate-700 rounded text-xs">
                            {keyword}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* No brand identity message */}
          {!site.seoConfig?.toneOfVoice && !site.seoConfig?.brandStory && !site.seoConfig?.trustSignals && !site.seoConfig?.contentGuidelines && (
            <Card>
              <CardContent className="p-8 text-center">
                <div className="text-4xl mb-4">🎨</div>
                <h3 className="text-lg font-medium text-slate-900">No Brand Identity Generated</h3>
                <p className="text-slate-500 mt-1 mb-4">
                  Brand identity (tone of voice, brand story, trust signals) hasn&apos;t been generated yet.
                </p>
                <p className="text-sm text-slate-400">
                  Go to the Sites page and click &quot;Generate Brand Identity&quot; to create brand guidelines for content generation.
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Pages Tab */}
      {activeTab === 'pages' && (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-slate-900">Pages ({site.pages.length})</h2>
          {site.pages.length === 0 ? (
            <Card>
              <CardContent className="p-8 text-center">
                <div className="text-4xl mb-4">📄</div>
                <h3 className="text-lg font-medium text-slate-900">No pages yet</h3>
                <p className="text-slate-500 mt-1">Pages will be created as content is generated</p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-3">
              {site.pages.map((page) => (
                <Card key={page.id}>
                  <CardContent className="p-4 flex items-center justify-between">
                    <div>
                      <h3 className="font-medium text-slate-900">{page.title}</h3>
                      <p className="text-sm text-slate-500">/{page.slug || '(homepage)'}</p>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-xs text-slate-400">{page.type}</span>
                      <span
                        className={`text-xs px-2 py-1 rounded ${
                          page.status === 'PUBLISHED'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-gray-100 text-gray-800'
                        }`}
                      >
                        {page.status}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Domains Tab */}
      {activeTab === 'domains' && (
        <div className="space-y-4">
          <h2 className="text-lg font-semibold text-slate-900">Domains</h2>

          {/* Suggested domain */}
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-medium text-slate-900">{site.suggestedDomain}</h3>
                  <p className="text-sm text-slate-500">
                    {site.primaryDomain ? 'Primary domain' : 'Suggested domain (not yet registered)'}
                  </p>
                </div>
                <span
                  className={`text-xs px-2 py-1 rounded ${
                    site.primaryDomain ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800'
                  }`}
                >
                  {site.primaryDomain ? 'Active' : 'Pending'}
                </span>
              </div>
            </CardContent>
          </Card>

          {/* Registered domains */}
          {site.domains.length > 0 && (
            <>
              <h3 className="text-md font-medium text-slate-700 mt-6">Registered Domains</h3>
              {site.domains.map((domain) => (
                <Card key={domain.id}>
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <h3 className="font-medium text-slate-900">{domain.domain}</h3>
                        <p className="text-sm text-slate-500">
                          SSL: {domain.sslEnabled ? 'Enabled' : 'Not configured'}
                          {domain.verifiedAt && ` • Verified ${formatDate(domain.verifiedAt)}`}
                        </p>
                      </div>
                      <span
                        className={`text-xs px-2 py-1 rounded ${
                          domain.status === 'ACTIVE'
                            ? 'bg-green-100 text-green-800'
                            : 'bg-gray-100 text-gray-800'
                        }`}
                      >
                        {domain.status}
                      </span>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </>
          )}
        </div>
      )}
    </div>
  );
}
