/**
 * Multi-tenant Site Management
 * Handles site identification, configuration loading, and theming
 */

// Local type declarations matching Prisma schema
// (to avoid dependency on @prisma/client generation)
interface Site {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  brandId: string | null;
  primaryDomain: string | null;
  holibobPartnerId: string;
  holibobApiKey: string | null;
  status: 'DRAFT' | 'REVIEW' | 'ACTIVE' | 'PAUSED' | 'ARCHIVED';
  isAutomatic: boolean;
  seoConfig: unknown;
  homepageConfig: unknown;
  gscVerificationCode: string | null;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
}

interface Brand {
  id: string;
  name: string;
  tagline: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  headingFont: string;
  bodyFont: string;
  logoUrl: string | null;
  logoDarkUrl: string | null; // Dark version of logo for transparent headers on hero images
  faviconUrl: string | null;
  ogImageUrl: string | null;
  socialLinks: unknown;
  isAutoGenerated: boolean;
  generationPrompt: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// Homepage configuration for site-specific customization
export interface HomepageConfig {
  hero?: {
    title?: string;
    subtitle?: string;
    backgroundImage?: string; // Unsplash image URL (hotlinked as required)
    // Unsplash attribution (REQUIRED when displaying images)
    backgroundImageAttribution?: {
      photographerName: string;
      photographerUrl: string; // Link to photographer profile
      unsplashUrl: string; // Link to Unsplash
    };
  };
  popularExperiences?: {
    title?: string;
    subtitle?: string;
    destination?: string; // e.g., "London" - passed to Holibob API
    categoryPath?: string; // e.g., "food-wine-and-beer-experiences"
    searchTerms?: string[];
  };
  destinations?: Array<{
    name: string;
    slug: string;
    icon: string; // emoji
    imageUrl?: string; // Unsplash image URL (hotlinked as required)
    description?: string; // AI-generated description for /destinations page
    // Unsplash attribution (REQUIRED when displaying images)
    imageAttribution?: {
      photographerName: string;
      photographerUrl: string; // Link to photographer profile
      unsplashUrl: string; // Link to Unsplash
    };
  }>;
  categories?: Array<{
    name: string;
    slug: string;
    icon: string; // emoji
    imageUrl?: string; // Unsplash image URL (hotlinked as required)
    description?: string; // AI-generated description for /categories page
    // Unsplash attribution (REQUIRED when displaying images)
    imageAttribution?: {
      photographerName: string;
      photographerUrl: string; // Link to photographer profile
      unsplashUrl: string; // Link to Unsplash
    };
  }>;
  testimonials?: Array<{
    name: string;
    location: string;
    text: string;
    rating: number;
  }>;
}

// Site configuration with brand info
export interface SiteConfig {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  primaryDomain: string | null;
  holibobPartnerId: string;
  gscVerificationCode: string | null;

  // Brand theming
  brand: {
    name: string;
    tagline: string | null;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    headingFont: string;
    bodyFont: string;
    logoUrl: string | null;
    logoDarkUrl: string | null; // Dark version of logo for transparent headers
    faviconUrl: string | null;
    ogImageUrl: string | null;
    socialLinks: Record<string, string> | null;
  } | null;

  // SEO Configuration
  seoConfig: {
    titleTemplate: string;
    defaultTitle?: string; // SEO-optimized homepage title (e.g. "Brand - Tagline | Location Niche")
    defaultDescription: string;
    keywords: string[];
    gaMeasurementId?: string | null; // Google Analytics 4 measurement ID
  } | null;

  // Homepage Configuration (AI-generated)
  homepageConfig: HomepageConfig | null;
}

// Default site configuration for development/fallback
export const DEFAULT_SITE_CONFIG: SiteConfig = {
  id: 'default',
  slug: 'default',
  name: 'Experience Marketplace',
  description: 'Discover unique experiences in your destination',
  primaryDomain: null,
  holibobPartnerId: process.env['HOLIBOB_PARTNER_ID'] ?? 'demo',
  gscVerificationCode: null,
  brand: {
    name: 'Experience Marketplace',
    tagline: 'Discover Unique Experiences',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    accentColor: '#f59e0b',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    logoUrl: null,
    logoDarkUrl: null,
    faviconUrl: null,
    ogImageUrl: null,
    socialLinks: null,
  },
  seoConfig: {
    titleTemplate: '%s | Experience Marketplace',
    defaultDescription:
      'Discover and book unique experiences, tours, and activities in your destination.',
    keywords: ['experiences', 'tours', 'activities', 'travel', 'booking'],
  },
  homepageConfig: {
    hero: {
      title: 'Discover Unique Experiences',
      subtitle: 'Find and book unforgettable tours, activities, and attractions worldwide',
    },
    popularExperiences: {
      title: 'Popular Experiences',
      subtitle: 'Discover the most loved experiences in your destination',
    },
    destinations: [
      {
        name: 'London',
        slug: 'london',
        icon: '🇬🇧',
        description:
          'Experience world-class culture, history, and entertainment in the UK capital.',
      },
      {
        name: 'Paris',
        slug: 'paris',
        icon: '🇫🇷',
        description: 'Discover romance, art, and culinary excellence in the City of Light.',
      },
      {
        name: 'Barcelona',
        slug: 'barcelona',
        icon: '🇪🇸',
        description: 'Enjoy stunning architecture, beaches, and vibrant Catalan culture.',
      },
      {
        name: 'Rome',
        slug: 'rome',
        icon: '🇮🇹',
        description: 'Walk through ancient history and savor authentic Italian experiences.',
      },
      {
        name: 'Amsterdam',
        slug: 'amsterdam',
        icon: '🇳🇱',
        description: 'Explore charming canals, world-class museums, and Dutch hospitality.',
      },
      {
        name: 'Edinburgh',
        slug: 'edinburgh',
        icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        description: 'Discover medieval charm and Scottish heritage in this historic capital.',
      },
      {
        name: 'Lisbon',
        slug: 'lisbon',
        icon: '🇵🇹',
        description: 'Experience colorful neighborhoods, delicious cuisine, and coastal beauty.',
      },
      {
        name: 'Berlin',
        slug: 'berlin',
        icon: '🇩🇪',
        description: 'Explore modern culture, fascinating history, and creative energy.',
      },
    ],
    categories: [
      {
        name: 'Tours & Sightseeing',
        slug: 'tours',
        icon: '🗺️',
        description:
          'Guided tours to discover the best of your destination with expert local guides.',
      },
      {
        name: 'Food & Drink',
        slug: 'food-drink',
        icon: '🍷',
        description:
          'Culinary adventures from street food to fine dining, wine tastings, and cooking classes.',
      },
      {
        name: 'Adventure',
        slug: 'adventure',
        icon: '🏔️',
        description:
          'Thrilling outdoor activities and adrenaline-pumping experiences for adventurers.',
      },
      {
        name: 'Culture & History',
        slug: 'culture',
        icon: '🏛️',
        description:
          'Immerse yourself in local heritage, museums, art galleries, and historical landmarks.',
      },
      {
        name: 'Water Activities',
        slug: 'water',
        icon: '🚤',
        description: 'Boats, cruises, kayaking, diving, and everything aquatic for water lovers.',
      },
      {
        name: 'Day Trips',
        slug: 'day-trips',
        icon: '🚗',
        description:
          'Explore beyond the city on exciting excursions to nearby attractions and hidden gems.',
      },
    ],
  },
};

/**
 * Get site configuration from hostname
 * In production, this would query the database
 */
export async function getSiteFromHostname(hostname: string): Promise<SiteConfig> {
  // Remove port and www prefix for matching
  const cleanHostname = hostname.split(':')[0]?.replace(/^www\./, '') ?? hostname;

  console.log('[Tenant] Looking up site for hostname:', hostname, 'cleaned:', cleanHostname);

  // Development: localhost or preview deployments
  if (
    cleanHostname === 'localhost' ||
    cleanHostname.includes('127.0.0.1') ||
    cleanHostname.includes('.vercel.app') ||
    cleanHostname.includes('.herokuapp.com')
  ) {
    console.log('[Tenant] Returning default config for development/preview hostname');
    return DEFAULT_SITE_CONFIG;
  }

  // In production, query the database for site by domain
  try {
    console.log('[Tenant] Attempting database lookup for domain:', cleanHostname);
    const { prisma } = await import('@experience-marketplace/database');

    // Find domain and its associated site
    const domain = await prisma.domain.findUnique({
      where: { domain: cleanHostname },
      include: {
        site: {
          include: {
            brand: true,
          },
        },
      },
    });

    console.log(
      '[Tenant] Domain lookup result:',
      domain ? { id: domain.id, domain: domain.domain, hasSite: !!domain.site } : 'not found'
    );

    if (domain?.site) {
      console.log('[Tenant] Found site:', domain.site.name, domain.site.slug);
      return mapSiteToConfig(domain.site as Site & { brand: Brand | null });
    }

    // Fallback: try to find site by slug matching subdomain
    const subdomain = cleanHostname.split('.')[0];
    if (subdomain) {
      const site = await prisma.site.findUnique({
        where: { slug: subdomain },
        include: { brand: true },
      });

      if (site) {
        return mapSiteToConfig(site as Site & { brand: Brand | null });
      }
    }
  } catch (error) {
    console.error('Error fetching site from database:', error);
  }

  return DEFAULT_SITE_CONFIG;
}

/**
 * Map database Site model to SiteConfig
 */
function mapSiteToConfig(site: Site & { brand: Brand | null }): SiteConfig {
  const seoConfig = site.seoConfig as {
    titleTemplate?: string;
    defaultTitle?: string;
    defaultDescription?: string;
    keywords?: string[];
    gaMeasurementId?: string | null;
  } | null;

  const homepageConfig = site.homepageConfig as HomepageConfig | null;

  return {
    id: site.id,
    slug: site.slug,
    name: site.name,
    description: site.description,
    primaryDomain: site.primaryDomain,
    holibobPartnerId: site.holibobPartnerId,
    gscVerificationCode: site.gscVerificationCode,
    brand: site.brand
      ? {
          name: site.brand.name,
          tagline: site.brand.tagline,
          primaryColor: site.brand.primaryColor,
          secondaryColor: site.brand.secondaryColor,
          accentColor: site.brand.accentColor,
          headingFont: site.brand.headingFont,
          bodyFont: site.brand.bodyFont,
          logoUrl: site.brand.logoUrl,
          logoDarkUrl: site.brand.logoDarkUrl,
          faviconUrl: site.brand.faviconUrl,
          ogImageUrl: site.brand.ogImageUrl,
          socialLinks: site.brand.socialLinks as Record<string, string> | null,
        }
      : null,
    seoConfig: seoConfig
      ? {
          titleTemplate: seoConfig.titleTemplate ?? '%s | ' + site.name,
          defaultTitle: seoConfig.defaultTitle,
          defaultDescription: seoConfig.defaultDescription ?? site.description ?? '',
          keywords: seoConfig.keywords ?? [],
          gaMeasurementId: seoConfig.gaMeasurementId ?? null,
        }
      : {
          titleTemplate: '%s | ' + site.name,
          defaultDescription: site.description ?? '',
          keywords: [],
          gaMeasurementId: null,
        },
    homepageConfig: homepageConfig,
  };
}

/**
 * Generate CSS variables from brand configuration
 */
export function generateBrandCSSVariables(brand: SiteConfig['brand']): string {
  if (!brand) {
    return '';
  }

  return `
    :root {
      --color-primary: ${brand.primaryColor};
      --color-secondary: ${brand.secondaryColor};
      --color-accent: ${brand.accentColor};
      --font-heading: ${brand.headingFont}, system-ui, sans-serif;
      --font-body: ${brand.bodyFont}, system-ui, sans-serif;
    }
  `.trim();
}
