/**
 * Multi-tenant Site Management
 * Handles site identification, configuration loading, and theming
 */

import { parseMicrositeHostname, type MicrositeParentDomain } from './microsite';
import { isParentDomain } from './parent-domain';
import {
  type MicrositeLayoutType,
  type MicrositeLayoutConfig,
  getLayoutConfig,
} from './microsite-layout';
import type { SupplierType } from './supplier';

// Local type declarations matching Prisma schema
// (to avoid dependency on @prisma/client generation)
interface Site {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  brandId: string | null;
  primaryDomain: string | null;
  holibobPartnerId: string;
  holibobApiKey: string | null;
  status: 'DRAFT' | 'REVIEW' | 'ACTIVE' | 'PAUSED' | 'ARCHIVED';
  isAutomatic: boolean;
  seoConfig: unknown;
  homepageConfig: unknown;
  gscVerificationCode: string | null;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
}

interface Brand {
  id: string;
  name: string;
  tagline: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  headingFont: string;
  bodyFont: string;
  logoUrl: string | null;
  logoDarkUrl: string | null; // Dark version of logo for transparent headers on hero images
  faviconUrl: string | null;
  ogImageUrl: string | null;
  socialLinks: unknown;
  isAutoGenerated: boolean;
  generationPrompt: string | null;
  createdAt: Date;
  updatedAt: Date;
}

// MicrositeConfig local type (matching Prisma schema)
interface MicrositeConfig {
  id: string;
  subdomain: string;
  parentDomain: string;
  fullDomain: string;
  entityType: 'SUPPLIER' | 'PRODUCT';
  supplierId: string | null;
  productId: string | null;
  brandId: string;
  siteName: string;
  tagline: string | null;
  seoConfig: unknown;
  homepageConfig: unknown;
  // Supplier type determines which API to use
  supplierType: 'HOLIBOB' | 'TICKITTO';
  tickittoConfig: unknown | null;
  // Layout configuration for microsite homepage
  layoutType: MicrositeLayoutType;
  cachedProductCount: number;
  productCountUpdatedAt: Date | null;
  status: 'DRAFT' | 'GENERATING' | 'REVIEW' | 'ACTIVE' | 'PAUSED' | 'ARCHIVED';
  autonomousProcessesPaused: boolean;
  pausedAt: Date | null;
  pausedBy: string | null;
  pauseReason: string | null;
  pageViews: number;
  lastContentUpdate: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

// Simple in-memory cache for microsite configs (short TTL)
// In production, this would be replaced with Redis caching
// Uses MicrositeConfigWithEntity to include supplier/product Holibob IDs
const micrositeCache = new Map<string, { config: unknown | null; expiresAt: number }>();
const MICROSITE_CACHE_TTL_MS = 60 * 1000; // 1 minute in-memory cache

// Homepage configuration for site-specific customization
export interface HomepageConfig {
  hero?: {
    title?: string;
    subtitle?: string;
    backgroundImage?: string; // Unsplash image URL (hotlinked as required)
    // Unsplash attribution (REQUIRED when displaying images)
    backgroundImageAttribution?: {
      photographerName: string;
      photographerUrl: string; // Link to photographer profile
      unsplashUrl: string; // Link to Unsplash
    };
  };
  popularExperiences?: {
    title?: string;
    subtitle?: string;
    destination?: string; // e.g., "London" - passed to Holibob API
    categoryPath?: string; // e.g., "food-wine-and-beer-experiences"
    searchTerms?: string[];
  };
  destinations?: Array<{
    name: string;
    slug: string;
    icon: string; // emoji
    imageUrl?: string; // Unsplash image URL (hotlinked as required)
    description?: string; // AI-generated description for /destinations page
    // Unsplash attribution (REQUIRED when displaying images)
    imageAttribution?: {
      photographerName: string;
      photographerUrl: string; // Link to photographer profile
      unsplashUrl: string; // Link to Unsplash
    };
  }>;
  categories?: Array<{
    name: string;
    slug: string;
    icon: string; // emoji
    imageUrl?: string; // Unsplash image URL (hotlinked as required)
    description?: string; // AI-generated description for /categories page
    // Unsplash attribution (REQUIRED when displaying images)
    imageAttribution?: {
      photographerName: string;
      photographerUrl: string; // Link to photographer profile
      unsplashUrl: string; // Link to Unsplash
    };
  }>;
  testimonials?: Array<{
    name: string;
    location: string;
    text: string;
    rating: number;
  }>;
}

// Microsite-specific context (only present for microsites)
export interface MicrositeContext {
  micrositeId: string; // The MicrositeConfig ID
  entityType: 'SUPPLIER' | 'PRODUCT';
  supplierId: string | null;
  productId: string | null;
  holibobSupplierId?: string | null; // For filtering Holibob API calls
  holibobProductId?: string | null; // For single product microsites
  supplierCities?: string[]; // Cities where supplier operates (for Holibob API search)
  supplierCategories?: string[]; // Categories the supplier operates in (for cross-linking)
  supplierName?: string | null; // Supplier name for search fallback
  // Supplier type - determines which API to use (default: HOLIBOB)
  supplierType: SupplierType;
  // Tickitto-specific config (only for TICKITTO supplier type)
  tickittoConfig?: { apiUrl?: string; eventFilters?: Record<string, unknown> } | null;
  // Layout configuration for microsite homepage
  layoutConfig: MicrositeLayoutConfig;
  // Cached product count from database (for accurate per-supplier counts)
  cachedProductCount: number;
}

// Site configuration with brand info
export interface SiteConfig {
  id: string;
  slug: string;
  name: string;
  description: string | null;
  primaryDomain: string | null;
  holibobPartnerId: string;
  gscVerificationCode: string | null;

  // Brand theming
  brand: {
    name: string;
    tagline: string | null;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    headingFont: string;
    bodyFont: string;
    logoUrl: string | null;
    logoDarkUrl: string | null; // Dark version of logo for transparent headers
    faviconUrl: string | null;
    ogImageUrl: string | null;
    socialLinks: Record<string, string> | null;
  } | null;

  // SEO Configuration
  seoConfig: {
    titleTemplate: string;
    defaultTitle?: string; // SEO-optimized homepage title (e.g. "Brand - Tagline | Location Niche")
    defaultDescription: string;
    keywords: string[];
    gaMeasurementId?: string | null; // Google Analytics 4 measurement ID
  } | null;

  // Homepage Configuration (AI-generated)
  homepageConfig: HomepageConfig | null;

  // Microsite context (only present for microsites on *.experiencess.com)
  micrositeContext?: MicrositeContext;

  // Parent domain flag (only true for experiencess.com root domain)
  isParentDomain?: boolean;
}

// Default site configuration for development/fallback
export const DEFAULT_SITE_CONFIG: SiteConfig = {
  id: 'default',
  slug: 'default',
  name: 'Experience Marketplace',
  description: 'Discover unique experiences in your destination',
  primaryDomain: null,
  holibobPartnerId: process.env['HOLIBOB_PARTNER_ID'] ?? 'demo',
  gscVerificationCode: null,
  brand: {
    name: 'Experience Marketplace',
    tagline: 'Discover Unique Experiences',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    accentColor: '#f59e0b',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    logoUrl: null,
    logoDarkUrl: null,
    faviconUrl: null,
    ogImageUrl: null,
    socialLinks: null,
  },
  seoConfig: {
    titleTemplate: '%s | Experience Marketplace',
    defaultDescription:
      'Discover and book unique experiences, tours, and activities in your destination.',
    keywords: ['experiences', 'tours', 'activities', 'travel', 'booking'],
  },
  homepageConfig: {
    hero: {
      title: 'Discover Unique Experiences',
      subtitle: 'Find and book unforgettable tours, activities, and attractions worldwide',
    },
    popularExperiences: {
      title: 'Popular Experiences',
      subtitle: 'Discover the most loved experiences in your destination',
    },
    destinations: [
      {
        name: 'London',
        slug: 'london',
        icon: '🇬🇧',
        description:
          'Experience world-class culture, history, and entertainment in the UK capital.',
      },
      {
        name: 'Paris',
        slug: 'paris',
        icon: '🇫🇷',
        description: 'Discover romance, art, and culinary excellence in the City of Light.',
      },
      {
        name: 'Barcelona',
        slug: 'barcelona',
        icon: '🇪🇸',
        description: 'Enjoy stunning architecture, beaches, and vibrant Catalan culture.',
      },
      {
        name: 'Rome',
        slug: 'rome',
        icon: '🇮🇹',
        description: 'Walk through ancient history and savor authentic Italian experiences.',
      },
      {
        name: 'Amsterdam',
        slug: 'amsterdam',
        icon: '🇳🇱',
        description: 'Explore charming canals, world-class museums, and Dutch hospitality.',
      },
      {
        name: 'Edinburgh',
        slug: 'edinburgh',
        icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        description: 'Discover medieval charm and Scottish heritage in this historic capital.',
      },
      {
        name: 'Lisbon',
        slug: 'lisbon',
        icon: '🇵🇹',
        description: 'Experience colorful neighborhoods, delicious cuisine, and coastal beauty.',
      },
      {
        name: 'Berlin',
        slug: 'berlin',
        icon: '🇩🇪',
        description: 'Explore modern culture, fascinating history, and creative energy.',
      },
    ],
    categories: [
      {
        name: 'Tours & Sightseeing',
        slug: 'tours',
        icon: '🗺️',
        description:
          'Guided tours to discover the best of your destination with expert local guides.',
      },
      {
        name: 'Food & Drink',
        slug: 'food-drink',
        icon: '🍷',
        description:
          'Culinary adventures from street food to fine dining, wine tastings, and cooking classes.',
      },
      {
        name: 'Adventure',
        slug: 'adventure',
        icon: '🏔️',
        description:
          'Thrilling outdoor activities and adrenaline-pumping experiences for adventurers.',
      },
      {
        name: 'Culture & History',
        slug: 'culture',
        icon: '🏛️',
        description:
          'Immerse yourself in local heritage, museums, art galleries, and historical landmarks.',
      },
      {
        name: 'Water Activities',
        slug: 'water',
        icon: '🚤',
        description: 'Boats, cruises, kayaking, diving, and everything aquatic for water lovers.',
      },
      {
        name: 'Day Trips',
        slug: 'day-trips',
        icon: '🚗',
        description:
          'Explore beyond the city on exciting excursions to nearby attractions and hidden gems.',
      },
    ],
  },
};

/**
 * Get site configuration from hostname
 * Supports both traditional sites (custom domains) and microsites (*.experiencess.com subdomains)
 */
export async function getSiteFromHostname(hostname: string): Promise<SiteConfig> {
  // Remove port and www prefix for matching
  const cleanHostname = hostname.split(':')[0]?.replace(/^www\./, '') ?? hostname;

  console.log('[Tenant] Looking up site for hostname:', hostname, 'cleaned:', cleanHostname);

  // === MICROSITE CHECK (EARLY EXIT) ===
  // Check if this is a microsite subdomain (e.g., adventure-co.experiencess.com)
  // This must happen BEFORE the development/preview check to allow testing microsites locally
  const micrositeInfo = parseMicrositeHostname(cleanHostname);
  if (micrositeInfo.isMicrositeSubdomain && micrositeInfo.subdomain && micrositeInfo.parentDomain) {
    console.log(
      '[Tenant] Detected microsite subdomain:',
      micrositeInfo.subdomain,
      'on',
      micrositeInfo.parentDomain
    );
    const micrositeConfig = await checkMicrositeSubdomain(
      micrositeInfo.subdomain,
      micrositeInfo.parentDomain
    );
    if (micrositeConfig) {
      console.log('[Tenant] Found microsite config for:', micrositeInfo.subdomain);
      return micrositeConfig;
    }
    // If microsite not found in DB, fall through to default config
    console.log('[Tenant] Microsite subdomain not found in database, returning default config');
    return DEFAULT_SITE_CONFIG;
  }
  // === END MICROSITE CHECK ===

  // === PARENT DOMAIN CHECK ===
  // For experiencess.com (the marketplace root), return parent domain config
  if (isParentDomain(cleanHostname)) {
    console.log('[Tenant] Parent domain detected:', cleanHostname);
    return {
      ...DEFAULT_SITE_CONFIG,
      name: 'Experiencess',
      description: 'A network of experience brands powered by Holibob',
      primaryDomain: cleanHostname,
      isParentDomain: true,
    };
  }
  // === END PARENT DOMAIN CHECK ===

  // Development: localhost or preview deployments
  if (
    cleanHostname === 'localhost' ||
    cleanHostname.includes('127.0.0.1') ||
    cleanHostname.includes('.vercel.app') ||
    cleanHostname.includes('.herokuapp.com')
  ) {
    console.log('[Tenant] Returning default config for development/preview hostname');
    return DEFAULT_SITE_CONFIG;
  }

  // In production, query the database for site by domain
  try {
    console.log('[Tenant] Attempting database lookup for domain:', cleanHostname);
    const { prisma } = await import('@experience-marketplace/database');

    // Find domain and its associated site
    const domain = await prisma.domain.findUnique({
      where: { domain: cleanHostname },
      include: {
        site: {
          include: {
            brand: true,
          },
        },
      },
    });

    console.log(
      '[Tenant] Domain lookup result:',
      domain ? { id: domain.id, domain: domain.domain, hasSite: !!domain.site } : 'not found'
    );

    if (domain?.site) {
      console.log('[Tenant] Found site:', domain.site.name, domain.site.slug);
      return mapSiteToConfig(domain.site as Site & { brand: Brand | null });
    }

    // Fallback: try to find site by slug matching subdomain
    const subdomain = cleanHostname.split('.')[0];
    if (subdomain) {
      const site = await prisma.site.findUnique({
        where: { slug: subdomain },
        include: { brand: true },
      });

      if (site) {
        return mapSiteToConfig(site as Site & { brand: Brand | null });
      }
    }
  } catch (error) {
    console.error('Error fetching site from database:', error);
  }

  return DEFAULT_SITE_CONFIG;
}

/**
 * Check if a hostname is a microsite subdomain and return its config
 * This is an early-exit check for *.experiencess.com subdomains
 */
async function checkMicrositeSubdomain(
  subdomain: string,
  parentDomain: MicrositeParentDomain
): Promise<SiteConfig | null> {
  try {
    const config = await getMicrositeConfig(subdomain, parentDomain);
    if (config) {
      return mapMicrositeToSiteConfig(config);
    }
  } catch (error) {
    console.error('[Tenant] Error checking microsite subdomain:', error);
  }
  return null;
}

// Extended microsite config with entity data for filtering
interface MicrositeConfigWithEntity extends MicrositeConfig {
  brand: Brand;
  supplier?: {
    holibobSupplierId: string;
    cities: string[];
    categories: string[];
    name: string;
  } | null;
  product?: { holibobProductId: string } | null;
}

/**
 * Get microsite configuration from database with caching
 * Uses in-memory cache with short TTL, can be extended to use Redis for production
 */
async function getMicrositeConfig(
  subdomain: string,
  parentDomain: string
): Promise<MicrositeConfigWithEntity | null> {
  const cacheKey = `microsite:${subdomain}:${parentDomain}`;
  const now = Date.now();

  // Check in-memory cache
  const cached = micrositeCache.get(cacheKey);
  if (cached && cached.expiresAt > now) {
    console.log('[Tenant] Microsite cache hit for:', cacheKey);
    return cached.config as MicrositeConfigWithEntity | null;
  }

  // Cache miss or expired - fetch from database
  console.log('[Tenant] Microsite cache miss, fetching from DB:', cacheKey);

  try {
    // Use dynamic import with type assertion for proper model access
    const { prisma } = (await import('@experience-marketplace/database')) as any;

    const config = await prisma.micrositeConfig.findUnique({
      where: {
        subdomain_parentDomain: {
          subdomain,
          parentDomain,
        },
      },
      include: {
        brand: true,
        // Include supplier/product to get their Holibob IDs, cities, and categories for API filtering
        supplier: {
          select: {
            holibobSupplierId: true,
            cities: true,
            categories: true,
            name: true,
          },
        },
        product: {
          select: { holibobProductId: true },
        },
      },
    });

    // Only return ACTIVE microsites for public access
    if (config && config.status === 'ACTIVE') {
      // Cache the result
      micrositeCache.set(cacheKey, {
        config: config as MicrositeConfigWithEntity,
        expiresAt: now + MICROSITE_CACHE_TTL_MS,
      });
      return config as MicrositeConfigWithEntity;
    }

    // Cache negative result to avoid repeated DB lookups
    micrositeCache.set(cacheKey, {
      config: null,
      expiresAt: now + MICROSITE_CACHE_TTL_MS,
    });
    return null;
  } catch (error) {
    console.error('[Tenant] Error fetching microsite config:', error);
    return null;
  }
}

/**
 * Map MicrositeConfig to the standard SiteConfig interface
 * This allows the rest of the app to work unchanged with microsites
 */
function mapMicrositeToSiteConfig(microsite: MicrositeConfigWithEntity): SiteConfig {
  const seoConfig = microsite.seoConfig as {
    titleTemplate?: string;
    defaultTitle?: string;
    defaultDescription?: string;
    keywords?: string[];
    gaMeasurementId?: string | null;
  } | null;

  const homepageConfig = microsite.homepageConfig as HomepageConfig | null;

  // Use default Holibob partner ID for microsites
  // Microsites are supplier/product-specific but use the platform's Holibob integration
  const holibobPartnerId = process.env['HOLIBOB_PARTNER_ID'] ?? 'demo';

  return {
    id: microsite.id,
    slug: microsite.subdomain, // Use subdomain as slug for microsites
    name: microsite.siteName,
    description: microsite.tagline,
    primaryDomain: microsite.fullDomain,
    holibobPartnerId,
    gscVerificationCode: null, // Microsites use domain-level GSC verification
    brand: {
      name: microsite.brand.name,
      tagline: microsite.brand.tagline,
      primaryColor: microsite.brand.primaryColor,
      secondaryColor: microsite.brand.secondaryColor,
      accentColor: microsite.brand.accentColor,
      headingFont: microsite.brand.headingFont,
      bodyFont: microsite.brand.bodyFont,
      // Generated logos disabled - using text-only branding (standard design) for all sites
      logoUrl: null,
      logoDarkUrl: null,
      faviconUrl: microsite.brand.faviconUrl,
      ogImageUrl: microsite.brand.ogImageUrl,
      socialLinks: microsite.brand.socialLinks as Record<string, string> | null,
    },
    seoConfig: seoConfig
      ? {
          titleTemplate: seoConfig.titleTemplate ?? '%s | ' + microsite.siteName,
          defaultTitle: seoConfig.defaultTitle,
          defaultDescription: seoConfig.defaultDescription ?? microsite.tagline ?? '',
          keywords: seoConfig.keywords ?? [],
          gaMeasurementId: seoConfig.gaMeasurementId ?? null,
        }
      : {
          titleTemplate: '%s | ' + microsite.siteName,
          defaultDescription: microsite.tagline ?? '',
          keywords: [],
          gaMeasurementId: null,
        },
    homepageConfig: homepageConfig,
    // Include microsite context for supplier/product filtering and layout
    micrositeContext: {
      micrositeId: microsite.id,
      entityType: microsite.entityType,
      supplierId: microsite.supplierId,
      productId: microsite.productId,
      holibobSupplierId: microsite.supplier?.holibobSupplierId ?? null,
      holibobProductId: microsite.product?.holibobProductId ?? null,
      supplierCities: microsite.supplier?.cities ?? [],
      supplierCategories: microsite.supplier?.categories ?? [],
      supplierName: microsite.supplier?.name ?? null,
      // Supplier type - determines which API to use
      supplierType: (microsite.supplierType as SupplierType) ?? 'HOLIBOB',
      tickittoConfig: microsite.tickittoConfig as { apiUrl?: string; eventFilters?: Record<string, unknown> } | null,
      // Cached product count from database (for accurate per-supplier counts in UI)
      cachedProductCount: microsite.cachedProductCount ?? 0,
      // Layout configuration based on product count
      layoutConfig: getLayoutConfig(
        microsite.layoutType ?? 'AUTO',
        microsite.cachedProductCount ?? 0
      ),
    },
  };
}

/**
 * Map database Site model to SiteConfig
 */
function mapSiteToConfig(site: Site & { brand: Brand | null }): SiteConfig {
  const seoConfig = site.seoConfig as {
    titleTemplate?: string;
    defaultTitle?: string;
    defaultDescription?: string;
    keywords?: string[];
    gaMeasurementId?: string | null;
  } | null;

  const homepageConfig = site.homepageConfig as HomepageConfig | null;

  return {
    id: site.id,
    slug: site.slug,
    name: site.name,
    description: site.description,
    primaryDomain: site.primaryDomain,
    holibobPartnerId: site.holibobPartnerId,
    gscVerificationCode: site.gscVerificationCode,
    brand: site.brand
      ? {
          name: site.brand.name,
          tagline: site.brand.tagline,
          primaryColor: site.brand.primaryColor,
          secondaryColor: site.brand.secondaryColor,
          accentColor: site.brand.accentColor,
          headingFont: site.brand.headingFont,
          bodyFont: site.brand.bodyFont,
          // Generated logos disabled - using text-only branding (standard design) for all sites
          logoUrl: null,
          logoDarkUrl: null,
          faviconUrl: site.brand.faviconUrl,
          ogImageUrl: site.brand.ogImageUrl,
          socialLinks: site.brand.socialLinks as Record<string, string> | null,
        }
      : null,
    seoConfig: seoConfig
      ? {
          titleTemplate: seoConfig.titleTemplate ?? '%s | ' + site.name,
          defaultTitle: seoConfig.defaultTitle,
          defaultDescription: seoConfig.defaultDescription ?? site.description ?? '',
          keywords: seoConfig.keywords ?? [],
          gaMeasurementId: seoConfig.gaMeasurementId ?? null,
        }
      : {
          titleTemplate: '%s | ' + site.name,
          defaultDescription: site.description ?? '',
          keywords: [],
          gaMeasurementId: null,
        },
    homepageConfig: homepageConfig,
  };
}

/**
 * Generate CSS variables from brand configuration
 */
export function generateBrandCSSVariables(brand: SiteConfig['brand']): string {
  if (!brand) {
    return '';
  }

  return `
    :root {
      --color-primary: ${brand.primaryColor};
      --color-secondary: ${brand.secondaryColor};
      --color-accent: ${brand.accentColor};
      --font-heading: ${brand.headingFont}, system-ui, sans-serif;
      --font-body: ${brand.bodyFont}, system-ui, sans-serif;
    }
  `.trim();
}
