-- Add new job types for DataForSEO intelligence features
ALTER TYPE "JobType" ADD VALUE 'LINK_COMPETITOR_DISCOVERY';
ALTER TYPE "JobType" ADD VALUE 'LINK_BROKEN_LINK_SCAN';
ALTER TYPE "JobType" ADD VALUE 'LINK_CONTENT_GAP_ANALYSIS';
