/**
 * Test factories for Site and Brand models.
 */

let siteCounter = 0;
let brandCounter = 0;

export function createMockBrand(overrides: Record<string, unknown> = {}) {
  brandCounter++;
  return {
    id: `brand-${brandCounter}`,
    name: `Test Brand ${brandCounter}`,
    tagline: 'Discover amazing experiences',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    accentColor: '#f59e0b',
    headingFont: 'Inter',
    bodyFont: 'Inter',
    logoUrl: null,
    faviconUrl: null,
    ogImageUrl: null,
    socialLinks: null,
    isAutoGenerated: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    ...overrides,
  };
}

export function createMockSite(overrides: Record<string, unknown> = {}) {
  siteCounter++;
  return {
    id: `site-${siteCounter}`,
    slug: `test-site-${siteCounter}`,
    name: `Test Site ${siteCounter}`,
    description: `Test description for site ${siteCounter}`,
    status: 'ACTIVE',
    isAutomatic: true,
    autonomousProcessesPaused: false,
    pauseReason: null,
    primaryDomain: `test-site-${siteCounter}.com`,
    holibobPartnerId: null,
    holibobApiKey: null,
    brandId: null,
    gscVerified: false,
    gscVerifiedAt: null,
    gscVerificationCode: null,
    seoConfig: null,
    homepageConfig: null,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    publishedAt: null,
    ...overrides,
  };
}

export function createMockSiteWithRelations(overrides: Record<string, unknown> = {}) {
  const brand = createMockBrand();
  const site = createMockSite({
    brandId: brand.id,
    brand,
    domains: [],
    pages: [],
    jobs: [],
    opportunities: [],
    _count: { pages: 0, content: 0, bookings: 0 },
    ...overrides,
  });
  return site;
}

export function createMockDomain(overrides: Record<string, unknown> = {}) {
  return {
    id: `domain-${Date.now()}`,
    domain: 'test-site.com',
    siteId: 'site-1',
    status: 'ACTIVE',
    cloudflareZoneId: null,
    dnsConfigured: false,
    sslEnabled: false,
    sslExpiresAt: null,
    verifiedAt: null,
    registrar: null,
    registeredAt: null,
    expiresAt: null,
    autoRenew: false,
    registrationCost: null,
    renewalCost: null,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    ...overrides,
  };
}
