/**
 * Type declarations for @experience-marketplace/database module
 * This file provides type safety when the Prisma client hasn't been generated
 */

declare module '@experience-marketplace/database' {
  // Minimal Prisma client interface for the methods we use
  interface PrismaClientLike {
    domain: {
      findUnique: (args: {
        where: { domain: string };
        include?: { site?: { include?: { brand?: boolean } } };
      }) => Promise<Domain | null>;
    };
    site: {
      findUnique: (args: {
        where: { slug: string };
        include?: { brand?: boolean };
      }) => Promise<Site | null>;
      findFirst: (args: {
        where: { slug: string };
        include?: { brand?: boolean };
      }) => Promise<Site | null>;
    };
  }

  export const prisma: PrismaClientLike;
  export const db: PrismaClientLike;

  // Re-export common Prisma types
  export interface Site {
    id: string;
    slug: string;
    name: string;
    description: string | null;
    brandId: string | null;
    primaryDomain: string | null;
    holibobPartnerId: string;
    holibobApiKey: string | null;
    status: 'DRAFT' | 'REVIEW' | 'ACTIVE' | 'PAUSED' | 'ARCHIVED';
    isAutomatic: boolean;
    seoConfig: unknown;
    createdAt: Date;
    updatedAt: Date;
    publishedAt: Date | null;
    brand?: Brand | null;
  }

  export interface Brand {
    id: string;
    name: string;
    tagline: string | null;
    primaryColor: string;
    secondaryColor: string;
    accentColor: string;
    headingFont: string;
    bodyFont: string;
    logoUrl: string | null;
    faviconUrl: string | null;
    ogImageUrl: string | null;
    socialLinks: unknown;
    isAutoGenerated: boolean;
    generationPrompt: string | null;
    createdAt: Date;
    updatedAt: Date;
  }

  export interface Domain {
    id: string;
    domain: string;
    siteId: string;
    site?: Site;
  }
}
