'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Card, CardContent } from '@experience-marketplace/ui-components';

interface Brand {
  name: string;
  tagline: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  headingFont: string;
  bodyFont: string;
  logoUrl: string | null;
  isAutoGenerated: boolean;
}

interface Site {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  status: 'DRAFT' | 'REVIEW' | 'ACTIVE' | 'PAUSED' | 'ARCHIVED';
  domain: string | null;
  suggestedDomain: string;
  monthlyVisitors: number;
  monthlyBookings: number;
  monthlyRevenue: number;
  brand: Brand | null;
  brandColor: string;
  pageCount?: number;
  domainCount?: number;
  createdAt: string;
}

interface Stats {
  totalSites: number;
  activeSites: number;
  draftSites: number;
  totalRevenue: number;
  totalVisitors: number;
}

export default function SitesPage() {
  const router = useRouter();
  const [sites, setSites] = useState<Site[]>([]);
  const [stats, setStats] = useState<Stats>({
    totalSites: 0,
    activeSites: 0,
    draftSites: 0,
    totalRevenue: 0,
    totalVisitors: 0,
  });
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [loading, setLoading] = useState(true);

  // Fetch sites from API
  useEffect(() => {
    const fetchSites = async () => {
      try {
        setLoading(true);
        const response = await fetch(`/admin/api/sites?status=${statusFilter}`);
        const data = await response.json();

        if (!response.ok || data.error) {
          console.error('API error:', data.error);
          setSites([]);
          return;
        }

        setSites(data.sites || []);
        setStats(data.stats || {
          totalSites: 0,
          activeSites: 0,
          draftSites: 0,
          totalRevenue: 0,
          totalVisitors: 0,
        });
      } catch (error) {
        console.error('Failed to fetch sites:', error);
        setSites([]);
      } finally {
        setLoading(false);
      }
    };

    fetchSites();
  }, [statusFilter]);

  const getStatusBadge = (status: Site['status']) => {
    const styles = {
      DRAFT: 'bg-gray-100 text-gray-800',
      REVIEW: 'bg-amber-100 text-amber-800',
      ACTIVE: 'bg-green-100 text-green-800',
      PAUSED: 'bg-blue-100 text-blue-800',
      ARCHIVED: 'bg-red-100 text-red-800',
    };
    return (
      <span className={`${styles[status]} text-xs px-2 py-1 rounded font-medium`}>{status}</span>
    );
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-slate-500">Loading sites...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Site Portfolio</h1>
          <p className="text-slate-500 mt-1">Manage your multi-site marketplace network</p>
        </div>
        <button className="px-4 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded-lg text-sm font-medium transition-colors">
          Create Site
        </button>
      </div>

      {/* Stats cards */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
        <Card className="cursor-pointer hover:shadow-md transition-shadow">
          <CardContent className="p-4">
            <p className="text-2xl font-bold text-slate-900">{stats.totalSites}</p>
            <p className="text-sm text-slate-500">Total Sites</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:shadow-md transition-shadow">
          <CardContent className="p-4">
            <p className="text-2xl font-bold text-green-600">{stats.activeSites}</p>
            <p className="text-sm text-slate-500">Active</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:shadow-md transition-shadow">
          <CardContent className="p-4">
            <p className="text-2xl font-bold text-amber-600">{stats.draftSites}</p>
            <p className="text-sm text-slate-500">In Progress</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:shadow-md transition-shadow">
          <CardContent className="p-4">
            <p className="text-2xl font-bold text-blue-600">
              {(stats.totalVisitors / 1000).toFixed(1)}k
            </p>
            <p className="text-sm text-slate-500">Monthly Visitors</p>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:shadow-md transition-shadow">
          <CardContent className="p-4">
            <p className="text-2xl font-bold text-purple-600">
              ${(stats.totalRevenue / 1000).toFixed(1)}k
            </p>
            <p className="text-sm text-slate-500">Monthly Revenue</p>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-4">
        <select
          value={statusFilter}
          onChange={(e) => setStatusFilter(e.target.value)}
          className="px-4 py-2 border border-slate-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-sky-500"
        >
          <option value="all">All Statuses</option>
          <option value="ACTIVE">Active</option>
          <option value="REVIEW">In Review</option>
          <option value="DRAFT">Draft</option>
          <option value="PAUSED">Paused</option>
          <option value="ARCHIVED">Archived</option>
        </select>
      </div>

      {/* Sites grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {sites.map((site) => (
          <Card key={site.id} className="overflow-hidden hover:shadow-lg transition-all">
            {/* Brand color bar */}
            <div className="h-2" style={{ backgroundColor: site.brandColor }} />
            <div className="p-6">
              {/* Header with Logo */}
              <div className="flex items-start gap-4 mb-4">
                {/* Logo placeholder or actual logo */}
                <div
                  className="w-16 h-16 rounded-lg flex items-center justify-center text-white text-xl font-bold shrink-0"
                  style={{ backgroundColor: site.brand?.primaryColor || site.brandColor }}
                >
                  {site.brand?.logoUrl ? (
                    <img
                      src={site.brand.logoUrl}
                      alt={site.name}
                      className="w-full h-full object-contain rounded-lg"
                    />
                  ) : (
                    site.name.charAt(0).toUpperCase()
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 mb-1">
                    <h3 className="text-lg font-semibold text-slate-900 truncate">{site.name}</h3>
                    {getStatusBadge(site.status)}
                  </div>
                  {/* Brand tagline / promise */}
                  {site.brand?.tagline && (
                    <p className="text-sm text-slate-600 italic mb-1">&ldquo;{site.brand.tagline}&rdquo;</p>
                  )}
                  {/* Domain info */}
                  <div className="flex items-center gap-2 text-sm">
                    {site.domain ? (
                      <a
                        href={`https://${site.domain}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-sky-600 hover:underline flex items-center gap-1"
                      >
                        {site.domain}
                        <span className="text-xs">↗</span>
                      </a>
                    ) : (
                      <span className="text-slate-500">
                        Planned: <span className="font-medium text-slate-700">{site.suggestedDomain}</span>
                      </span>
                    )}
                  </div>
                </div>
              </div>

              {/* Brand Details Section */}
              {site.brand && (
                <div className="mb-4 p-3 bg-slate-50 rounded-lg">
                  <div className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-2">Brand Identity</div>
                  <div className="grid grid-cols-2 gap-3">
                    {/* Color Palette */}
                    <div>
                      <div className="text-xs text-slate-500 mb-1">Colors</div>
                      <div className="flex items-center gap-1">
                        <div
                          className="w-6 h-6 rounded border border-slate-200"
                          style={{ backgroundColor: site.brand.primaryColor }}
                          title={`Primary: ${site.brand.primaryColor}`}
                        />
                        <div
                          className="w-6 h-6 rounded border border-slate-200"
                          style={{ backgroundColor: site.brand.secondaryColor }}
                          title={`Secondary: ${site.brand.secondaryColor}`}
                        />
                        <div
                          className="w-6 h-6 rounded border border-slate-200"
                          style={{ backgroundColor: site.brand.accentColor }}
                          title={`Accent: ${site.brand.accentColor}`}
                        />
                      </div>
                    </div>
                    {/* Typography */}
                    <div>
                      <div className="text-xs text-slate-500 mb-1">Typography</div>
                      <div className="text-sm text-slate-700">
                        {site.brand.headingFont}
                        {site.brand.bodyFont !== site.brand.headingFont && ` / ${site.brand.bodyFont}`}
                      </div>
                    </div>
                  </div>
                  {site.brand.isAutoGenerated && (
                    <div className="mt-2 text-xs text-slate-400">✨ AI-generated brand</div>
                  )}
                </div>
              )}

              {/* Site Description */}
              {site.description && (
                <div className="mb-4">
                  <div className="text-xs font-medium text-slate-500 uppercase tracking-wide mb-1">About</div>
                  <p className="text-sm text-slate-600 line-clamp-2">{site.description}</p>
                </div>
              )}

              {/* Metrics for Active Sites */}
              {site.status === 'ACTIVE' ? (
                <div className="grid grid-cols-3 gap-3 mb-4">
                  <div className="text-center p-3 bg-slate-50 rounded-lg">
                    <div className="text-lg font-bold text-slate-900">
                      {(site.monthlyVisitors / 1000).toFixed(1)}k
                    </div>
                    <div className="text-xs text-slate-500">Visitors/mo</div>
                  </div>
                  <div className="text-center p-3 bg-slate-50 rounded-lg">
                    <div className="text-lg font-bold text-slate-900">{site.monthlyBookings}</div>
                    <div className="text-xs text-slate-500">Bookings/mo</div>
                  </div>
                  <div className="text-center p-3 bg-slate-50 rounded-lg">
                    <div className="text-lg font-bold text-slate-900">
                      ${(site.monthlyRevenue / 1000).toFixed(1)}k
                    </div>
                    <div className="text-xs text-slate-500">Revenue/mo</div>
                  </div>
                </div>
              ) : (
                <div className="mb-4 p-3 bg-amber-50 rounded-lg">
                  <div className="text-sm text-amber-800">
                    {site.status === 'REVIEW' && '⏳ Site pending review and approval'}
                    {site.status === 'DRAFT' && '📝 Site in draft mode - content being generated'}
                    {site.status === 'PAUSED' && '⏸️ Site is paused'}
                  </div>
                </div>
              )}

              {/* Info */}
              <div className="flex items-center justify-between text-xs text-slate-500 mb-4">
                <span>{site.pageCount || 0} pages</span>
                <span>Created {new Date(site.createdAt).toLocaleDateString()}</span>
              </div>

              {/* Actions */}
              <div className="flex items-center gap-2">
                <button
                  onClick={() => router.push(`/sites/${site.id}`)}
                  className="flex-1 px-3 py-2 border border-slate-200 hover:bg-slate-50 rounded-lg text-sm font-medium transition-colors"
                >
                  View Details
                </button>
                <button
                  onClick={() => router.push(`/sites/${site.id}`)}
                  className="flex-1 px-3 py-2 bg-sky-600 hover:bg-sky-700 text-white rounded-lg text-sm font-medium transition-colors"
                >
                  Manage
                </button>
              </div>
            </div>
          </Card>
        ))}
      </div>

      {sites.length === 0 && (
        <Card>
          <CardContent className="p-12 text-center">
            <div className="text-4xl mb-4">🌐</div>
            <h3 className="text-lg font-medium text-slate-900">No sites found</h3>
            <p className="text-slate-500 mt-1">Try adjusting your filters or create a new site</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
