-- Add missing JobType enum values that exist in the Prisma schema
-- but were never migrated to the PostgreSQL database.

ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'SEO_AUTO_OPTIMIZE';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'GA4_SETUP';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'LINK_OPPORTUNITY_SCAN';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'LINK_BACKLINK_MONITOR';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'LINK_OUTREACH_GENERATE';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'LINK_ASSET_GENERATE';
