/**
 * Inspect the actual keyword seeds generated by the enrichment pipeline.
 * Uses the real pipeline code so results exactly match production behavior.
 *
 * Usage: node packages/jobs/dist/scripts/inspect-seeds.js [count]
 */
import { runBulkEnrichment } from '../services/keyword-enrichment';

async function main() {
  const count = parseInt(process.argv[2] || '20', 10);

  console.log(`Running enrichment dry-run for top ${count} suppliers...\n`);

  const result = await runBulkEnrichment({
    maxSuppliersPerRun: count,
    maxProductsPerSupplier: 30,
    skipDataForSeo: true,
    dryRun: true,
  });

  console.log('\n=== RESULT ===');
  console.log(`Suppliers processed: ${result.suppliersProcessed}`);
  console.log(`Products analyzed: ${result.productsAnalyzed}`);
  console.log(`Unique seeds: ${result.uniqueSeedsAfterDedup}`);
  console.log(`Duration: ${(result.duration / 1000).toFixed(1)}s`);
  console.log(`Errors: ${result.errors.length}`);

  if (result.errors.length > 0) {
    console.log('\nErrors:');
    for (const e of result.errors) console.log(`  ${e}`);
  }
}

main().catch((e) => {
  console.error('ERROR:', e.message);
  process.exit(1);
});
