import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // Create a sample brand
  const brand = await prisma.brand.create({
    data: {
      name: 'Barcelona Adventures',
      tagline: 'Discover the Magic of Barcelona',
      primaryColor: '#e11d48',
      secondaryColor: '#be123c',
      accentColor: '#fbbf24',
      headingFont: 'Poppins',
      bodyFont: 'Inter',
      isAutoGenerated: false,
      socialLinks: {
        instagram: 'https://instagram.com/barcelona-adventures',
        facebook: 'https://facebook.com/barcelona-adventures',
      },
    },
  });

  console.log('✅ Created brand:', brand.name);

  // Create a sample site
  const site = await prisma.site.create({
    data: {
      slug: 'barcelona-adventures',
      name: 'Barcelona Adventures',
      description: 'The ultimate guide to experiences in Barcelona',
      brandId: brand.id,
      holibobPartnerId: process.env.HOLIBOB_PARTNER_ID || 'demo-partner',
      status: 'ACTIVE',
      isAutomatic: true,
      seoConfig: {
        titleTemplate: '%s | Barcelona Adventures',
        defaultDescription:
          'Discover amazing tours, activities, and experiences in Barcelona. Book tickets online with instant confirmation.',
        keywords: ['barcelona tours', 'barcelona activities', 'things to do in barcelona'],
      },
    },
  });

  console.log('✅ Created site:', site.name);

  // Create a sample domain
  const domain = await prisma.domain.create({
    data: {
      domain: 'barcelona-adventures.example.com',
      status: 'ACTIVE',
      sslEnabled: true,
      dnsConfigured: true,
      siteId: site.id,
    },
  });

  console.log('✅ Created domain:', domain.domain);

  // Update site with primary domain
  await prisma.site.update({
    where: { id: site.id },
    data: { primaryDomain: domain.domain },
  });

  // Create sample pages
  const homepage = await prisma.page.create({
    data: {
      slug: '',
      type: 'HOMEPAGE',
      title: 'Barcelona Adventures - Tours & Activities',
      metaTitle: 'Barcelona Adventures | Best Tours & Activities in Barcelona',
      metaDescription:
        'Discover the best tours, activities, and experiences in Barcelona. Book online with instant confirmation and skip-the-line access.',
      status: 'PUBLISHED',
      siteId: site.id,
      publishedAt: new Date(),
    },
  });

  const categoryPage = await prisma.page.create({
    data: {
      slug: 'tours',
      type: 'CATEGORY',
      title: 'Barcelona Tours',
      metaTitle: 'Best Barcelona Tours 2026 | Guided Tours & Day Trips',
      metaDescription:
        'Explore Barcelona with our curated selection of guided tours. From Gaudi architecture to wine tasting, find your perfect Barcelona tour.',
      status: 'PUBLISHED',
      siteId: site.id,
      publishedAt: new Date(),
    },
  });

  console.log('✅ Created pages:', homepage.title, categoryPage.title);

  // Create sample SEO opportunity
  const opportunity = await prisma.sEOOpportunity.create({
    data: {
      keyword: 'sagrada familia skip the line tickets',
      searchVolume: 12000,
      difficulty: 45,
      cpc: 2.5,
      intent: 'TRANSACTIONAL',
      niche: 'barcelona-attractions',
      location: 'ES',
      priorityScore: 85,
      status: 'IDENTIFIED',
      source: 'manual',
    },
  });

  console.log('✅ Created SEO opportunity:', opportunity.keyword);

  // Create sample content
  const content = await prisma.content.create({
    data: {
      body: `# Welcome to Barcelona Adventures

Discover the magic of Barcelona with our curated selection of tours, activities, and experiences.
From the stunning architecture of Antoni Gaudí to the vibrant energy of Las Ramblas,
we help you experience the best of this incredible city.

## Why Book With Us?

- **Instant Confirmation** - Get your tickets immediately
- **Skip-the-Line Access** - No waiting in queues
- **Local Experts** - Guides who know Barcelona inside out
- **Best Price Guarantee** - We match any lower price

## Popular Categories

- Gaudi Architecture Tours
- Food & Wine Experiences
- Day Trips from Barcelona
- Flamenco Shows
- Sailing & Beach Activities`,
      bodyFormat: 'MARKDOWN',
      isAiGenerated: false,
      qualityScore: 92,
      seoScore: 88,
      siteId: site.id,
    },
  });

  // Link content to homepage
  await prisma.page.update({
    where: { id: homepage.id },
    data: { contentId: content.id },
  });

  console.log('✅ Created and linked content');

  console.log('🎉 Database seed completed successfully!');
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error('❌ Seed error:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
