-- Add analytics-related JobType enum values
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'GA4_DAILY_SYNC';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'REFRESH_ANALYTICS_VIEWS';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'MICROSITE_GSC_SYNC';
ALTER TYPE "JobType" ADD VALUE IF NOT EXISTS 'MICROSITE_ANALYTICS_SYNC';
